spring:
  application:
    name: streamacho-security
  session:
    store-type: redis
    redis:
      flush-mode: ON_SAVE
      namespace: streamacho
  datasource:
    url: jdbc:postgresql://localhost:55432/streamacho-security
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  mail:
    host: smtp.gmail.com
    port: 587
    username: streamacho@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true
    password: 42asd87!f0A
    default-encoding: UTF-8
  thymeleaf:
    encoding: UTF-8

mail:
  extended:
    no_reply_address: 'no-reply@streamacho.com'

routes:
  changePasswordTemplate: 'http://localhost:8080/users/change-password?token=%s'
  frontendOrigins:
    - 'https://localhost'
    - 'http://localhost:8080'
  verification_template: 'http://localhost:8080/#/activate?token=%s'
server:
  port: 0
  servlet:
    context-path: /api/users

eureka:
  client:
    registerWithEureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: ${discovery-service.uri:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
