spring:
  application:
    name: streamacho-meetings
  data:
    elasticsearch:
      cluster-name: jgBay-cluster
      cluster-nodes: localhost:9300
  datasource:
    url: jdbc:postgresql://localhost:55433/streamacho-meetings
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: streamacho@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true
    password: 42asd87!f0A
    default-encoding: UTF-8
  thymeleaf:
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  profiles:
    active: dev
  session:
    store-type: redis
    redis:
      flush-mode: ON_SAVE
      namespace: streamacho

cloudinary:
  api-key: 385895442613275
  api-secret: 0Z3cr7Jvz9huUr1u21RihU-FE5A
  cloud-name: dc27vxrfo

openvidu:
  secret: MY_SECRET
  url: https://localhost:8443/

server:
  port: 0
  servlet:
    context-path: /api/meetings

eureka:
  client:
    registerWithEureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: ${discovery-service.uri:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

mail:
  extended:
    no_reply_address: 'no-reply@streamacho.com'

routes:
  frontendOrigins:
      - 'https://localhost'
      - 'http://localhost:8080'
  roomInvitationTemplate: 'http://localhost:8080/#/rooms/%s'
