spring:
  application:
    name: streamacho-meetings
  session:
    store-type: redis
    redis:
      flush-mode: ON_SAVE
      namespace: streamacho
  datasource:
    url: jdbc:postgresql://localhost:55433/streamacho-meetings
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

openvidu:
  secret: MY_SECRET
  url: https://localhost:8443/

server:
  port: 0
  servlet:
    context-path: /api/meetings

eureka:
  client:
    registerWithEureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: ${discovery-service.uri:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

routes:
  frontendOrigin: 'http://localhost:8080'