version: '3'

services:
  streamacho-security-database:
    image: postgres
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: streamacho-security
    ports: 
     - 55432:5432
  
  streamacho-session-redis:
    image: redis
    ports:
     - 6379:6379

  streamacho-meetings-database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: streamacho-meetings
    ports:
     - 55433:5432

  streamacho-openvidu:
    image: openvidu/openvidu-server-kms
    environment:
      openvidu.secret: MY_SECRET
      KMS_STUN_IP: stun.l.google.com
      KMS_STUN_PORT: 19302
    ports:
      - 8443:8443
