version: '3'

services:
  streamacho-discovery-server:
    build:
      context: discovery-server/
      dockerfile: build/docker/Dockerfile
    network_mode: host

  streamacho-security-service:
    build:
      context: security/
      dockerfile: build/docker/Dockerfile
    network_mode: host
    depends_on:
      - streamacho-discovery-server
      - streamacho-security-database
      - streamacho-session-redis

  streamacho-chat-service:
    build:
      context: chat/
      dockerfile: build/docker/Dockerfile
    depends_on:
      - streamacho-discovery-server
      - streamacho-chat-rabbitmq
      - streamacho-chat-database
      - streamacho-chat-db-service
    network_mode: host
    ports:
      - 8091:8091

  streamacho-chat-db-service:
    build:
      context: chat-db/
      dockerfile: build/docker/Dockerfile
    network_mode: host
    depends_on:
      - streamacho-discovery-server
      - streamacho-chat-rabbitmq
      - streamacho-chat-database

  streamacho-chat-service:
    build:
      context: chat/
      dockerfile: build/docker/Dockerfile
    network_mode: host
    depends_on:
      - streamacho-chat-rabbitmq

  streamacho-meetings-service:
    build:
      context: meeting/
      dockerfile: build/docker/Dockerfile
    network_mode: host
    depends_on:
      - streamacho-discovery-server
      - streamacho-meetings-database
      - streamacho-session-redis

  streamacho-gateway-service:
    build:
      context: gateway/
      dockerfile: build/docker/Dockerfile
    network_mode: host
    depends_on:
      - streamacho-discovery-server
      - streamacho-security-service
      - streamacho-meetings-service
    healthcheck:
      test: curl -f http://localhost:8889/actuator/health
      interval: 5s
      retries: 100

  streamacho-security-database:
    image: postgres:alpine
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: streamacho-security
    ports: 
     - 55432:5432

  streamacho-meetings-database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: streamacho-meetings
    ports:
     - 55433:5432

  streamacho-chat-database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: streamacho-chat
    ports:
     - 55434:5432

  streamacho-chat-rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - 25672:25672
      - 15672:15672
      - 5672:5672
      - 4369:4369

  streamacho-openvidu:
    image: openvidu/openvidu-server-kms
    environment:
      openvidu.secret: MY_SECRET
      KMS_STUN_IP: stun.l.google.com
      KMS_STUN_PORT: 19302
    ports:
      - 8443:8443

  streamacho-session-redis:
    image: redis:alpine
    ports:
     - 6379:6379

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
      ports:
        - 9200:9200
        - 9300:9300
      volumes:
        - esdata:/usr/share/elasticsearch/data
      environment:
        - discovery.type=single-node
        - cluster.name=jgBay-cluster
        - bootstrap.memory_lock=true
        - xpack.security.enabled=false
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536

volumes:
  esdata:
    driver: local
