eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: ${discovery-service.uri:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    secure-port-enabled: true
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: streamacho-security
        uri: lb:http://streamacho-security
        predicates:
        - Path=/api/users/**
      - id: streamacho-security
        uri: lb:http://streamacho-meetings
        predicates:
        - Path=/api/meetings/**
      - id: streamacho-chat-ws
        order: 8888
        uri: lb:ws://streamacho-chat
        predicates:
        - Path=/api/chat/**
      - id: streamacho-chat
        uri: lb://streamacho-chat
        predicates:
        - Path=/api/chat/**
      - id: streamacho-chat-db
        uri: lb://streamacho-chat-db
        predicates:
        - Path=/api/chat-db/**

management:
  server:
    ssl:
      enabled: false
    port: 8889

server:
  port: 8888
  ssl:
    key-store-type: JKS
    key-store: classpath:keystore.jks
    key-alias: streamacho-gateway
    key-store-password: streamacho
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
