version: '2'
services:
  client:
    container_name: client
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - '.:/usr/src/client'
      - '/usr/src/client/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
